package de.haevn.snippetmanage.note;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import de.haevn.snippetmanage.common.annotation.PDFService;
import de.haevn.snippetmanage.common.exception.BadRequestException;
import de.haevn.snippetmanage.common.exception.NotFoundException;
import de.haevn.snippetmanage.common.utils.Patcher;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.Optional;

@Service
class NoteService {
    private final Patcher patcher;
    private final NoteRepository repository;

    public NoteService(Patcher patcher, NoteRepository repository) {
        this.patcher = patcher;
        this.repository = repository;
    }

    public boolean createNote(Note note) {
        repository.save(note);
        return true;
    }

    public boolean updateNote(Note note, String id) {
        var existingNote = repository.findAll().stream().filter(n -> n.getId().equalsIgnoreCase(id)).findFirst().orElseThrow(NotFoundException::new);
        patcher.patch(existingNote, note);
        repository.save(existingNote);
        return true;
    }

    public boolean deleteNote(String id) {
        if (id == null || !repository.existsById(id)) return false;

        repository.deleteById(id);
        return true;
    }

    public Optional<Note> getNote(String id) {
        if (id == null || !repository.existsById(id)) return Optional.empty();

        return repository.findById(id);
    }

    public List<Note> getAllNotes() {
        return repository.findAll();
    }

    public Integer getTextLimit() {
        return 4096;
    }

    public Optional<byte[]> printNoteToPDF(final String id) {
        Note note = repository.findById(id).orElseThrow(NotFoundException::new);
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Document document = new Document();
            PdfWriter.getInstance(document, baos);
            document.open();

            new PDFService("Note Export")
                    .addTitle("Note " + id)
                    .addKeywords("Note", "DashboardManager")
                    .appendToDoc(document);

            Font titleFont = new Font(Font.HELVETICA, 18, Font.BOLD);
            document.add(new Paragraph(note.getTitle(), titleFont));
            document.add(new Paragraph(" "));
            document.add(new Paragraph("Note ID: " + id));
            document.add(new Paragraph(" "));
            if (note.getCreatedAt() != null) {
                document.add(new Paragraph("Created at: " + note.getCreatedAt()));
                document.add(new Paragraph(" "));
            }
            if (note.getUpdatedAt() != null) {
                document.add(new Paragraph("Last update at: " + note.getUpdatedAt()));
                document.add(new Paragraph(" "));
            }

            document.add(new Paragraph(" "));


            if (note.getContent() == null || note.getContent().isBlank()) {
                document.add(new Paragraph("No content available."));
            } else {
                document.add(new Paragraph(note.getContent()));
            }

            document.add(new Paragraph(" "));
            document.add(new Footnote("Generated by DashboardManager"));

            document.close();
            return Optional.of(baos.toByteArray());
        } catch (DocumentException | java.io.IOException e) {
            throw new BadRequestException("PDF creation failed: " + e.getMessage());
        }
    }
}
